
package com.douglas.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExemploService", targetNamespace = "http://douglas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExemploService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcula", targetNamespace = "http://douglas.com/", className = "com.douglas.cliente.Calcula")
    @ResponseWrapper(localName = "calculaResponse", targetNamespace = "http://douglas.com/", className = "com.douglas.cliente.CalculaResponse")
    @Action(input = "http://douglas.com/ExemploService/calculaRequest", output = "http://douglas.com/ExemploService/calculaResponse")
    public int calcula(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNome", targetNamespace = "http://douglas.com/", className = "com.douglas.cliente.GetNome")
    @ResponseWrapper(localName = "getNomeResponse", targetNamespace = "http://douglas.com/", className = "com.douglas.cliente.GetNomeResponse")
    @Action(input = "http://douglas.com/ExemploService/getNomeRequest", output = "http://douglas.com/ExemploService/getNomeResponse")
    public String getNome();

}
